// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"xs.bbs/pkg/log"

	"github.com/google/wire"
	"xs.bbs/internal/app"
	"xs.bbs/internal/app/user/controller"
	"xs.bbs/internal/app/user/dao"
	"xs.bbs/internal/app/user/service"
	"xs.bbs/pkg/conf"
	"xs.bbs/pkg/database"
)

// Injectors from wire.go:

func initWebApp() (*app.WebApp, error) {
	config, err := conf.Init()
	if err != nil {
		return nil, err
	}
	if err := log.Init(config); err != nil {
		return nil, err
	}
	engine, err := app.InitEngine(config)
	if err != nil {
		return nil, err
	}
	db := database.Init(config)
	userDao := &dao.UserDao{
		DB: db,
	}
	userService := &service.UserService{
		Dao: userDao,
	}
	userController, err := controller.NewUseController(engine, userService)
	if err != nil {
		return nil, err
	}
	webApp := &app.WebApp{
		Engine:   engine,
		Config:   config,
		UserCtrl: userController,
	}
	return webApp, nil
}

// wire.go:

var controllerSet = wire.NewSet(controller.NewUseController)
