app_name: "myApp"
mode: "dev"
port: 8090
version: "v0.0.1"
start_time: "2020-10-01"
machine_id: 1

log:
  prefix: "[my-app]"
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "study"
  max_open_conns: 100
  max_idle_conns: 20

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100