basePath: /api/
definitions:
  ginx.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  model.SignUpParam:
    properties:
      nickName:
        description: s
        type: string
      password:
        description: s
        type: string
      rePassword:
        description: s
        type: string
      username:
        description: s
        type: string
    required:
    - password
    - username
    type: object
  model.UserDto:
    properties:
      email:
        description: 邮箱
        type: string
      nickname:
        description: 昵称
        type: string
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
host: 127.0.0.1:8090
info:
  contact:
    email: support@swagger.io
    name: 这里写联系人信息
    url: http://www.swagger.io/support
  description: 这是一个gin web开发脚手架
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: 项目标题
  version: 0.0.1
paths:
  /user/Get:
    get:
      consumes:
      - application/json
      description: 根据id获取用户
      operationId: /user/Get
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.UserDto'
              type: object
      summary: 根据id获取用户
      tags:
      - 用户接口
  /user/delete:
    get:
      consumes:
      - application/json
      description: 根据id删除用户
      operationId: /user/delete
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 根据id删除用户
      tags:
      - 用户接口
  /user/signup:
    post:
      consumes:
      - application/json
      description: 用户注册
      operationId: /user/signup
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.SignUpParam'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.UserDto'
              type: object
      summary: 用户注册账号
      tags:
      - 用户接口
swagger: "2.0"
